name: Test all

on:
  pull_request:
    branches: ["main"]

  push:
    branches:
    - ci-test/*

  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  build-test:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: unset NO_COLOR; unset NO_STYLE; zig build test
